version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
environment:
  BUILD_NUMBER: $(APPVEYOR_BUILD_NUMBER)
build_script:
- cmd: build.cmd
nuget:
  disable_publish_on_pr: true
test: off
artifacts:
- path: '**\*.binlog'
- path: '**\*.log'
- path: '**\*.nupkg'
deploy: off
